openapi: 3.0.3
info:
  title: Speckify
  description: Speckify
  version: 1.0.0
servers:
  - url: "https://speckify.com"
paths:
  /applications/{applicationId}:
    get:
      parameters:
        - name: applicationId
          in: query
          required: true
          schema:
            type: string
          example: 0f2d8657-8765-4177-b29e-7a3bf40da723
      responses:
        200:
          description: Hello World
          content:
            "text/plain":
              example: "Hello World"
          
  /ping:
    get:
      responses:
        200:
          description: Ping endpoint
          content:
            text/plain:
              example: pong
